import { Product } from '@/types/ecommerce';

export const MOCK_PRODUCTS: Product[] = [
  // --- PANTRY & CONFECTIONERY ---
  {
    id: 'prod-001',
    slug: 'kirkland-unsalted-mixed-nuts-2-5lb',
    gtin: '096619284218',
    name: 'Kirkland Extra Fancy Unsalted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Premium mix of cashews, almonds, pistachios, and macadamia nuts roasted without salt (2.5 lb / 1.13 kg).',
    price: 18.99,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-unsalted-mixed-nuts-2-5lb.avif', altText: 'Kirkland Unsalted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 140,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    slug: 'kirkland-salted-mixed-nuts-2-5lb',
    gtin: '096619164557',
    name: 'Kirkland Extra Fancy Salted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Roasted mixed nuts with cashews, almonds, pecans, Brazil nuts, and macadamias lightly salted (2.5 lb / 1.13 kg).',
    price: 18.99,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-unsalted-mixed-nuts-2-5lb-blue.jfif', altText: 'Kirkland Salted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.8,
    reviewCount: 95,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    slug: 'lindt-lindor-assorted-truffles-21-2oz',
    gtin: '003746601633',
    name: 'Lindt LINDOR Assorted Chocolate Truffles',
    brand: 'Lindt',
    categorySlug: 'pantry',
    subCategorySlug: 'confectionery',
    description: 'Irresistibly smooth assorted chocolate truffles including milk, dark, white, and extra dark (21.2 oz / 600g).',
    price: 16.99,
    currency: 'BIRR',
    images: [{ url: '/products/lindt-lindor-assorted-truffles-21-2oz.avif', altText: 'Lindt Lindor Assorted Truffles', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.9,
    reviewCount: 210,
    specifications: [{ label: 'Weight', value: '21.2 oz (600 g)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    slug: 'nutella-hazelnut-spread-2-pack',
    gtin: '009800895200',
    name: 'Nutella Hazelnut Spread with Cocoa (2 Pack)',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'spreads',
    description: 'Original rich hazelnut and cocoa spread bundle (Two 33.5 oz / 950g jars).',
    price: 15.49,
    currency: 'BIRR',
    images: [{ url: '/products/nutella-hazelnut-spread-2-pack.avif', altText: 'Nutella Hazelnut Spread Twin Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 25,
    ratingAverage: 5.0,
    reviewCount: 310,
    specifications: [{ label: 'Net Weight', value: '67 oz Total (2 x 33.5 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    slug: 'mayorga-organic-chia-seeds-3lb',
    gtin: '089708000215',
    name: 'Mayorga Organics BIRRA Chia Seeds',
    brand: 'Mayorga Organics',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Small farmer direct organic non-GMO gluten-free chia seeds (3 lb / 1.36 kg).',
    price: 11.99,
    currency: 'BIRR',
    images: [{ url: '/products/mayorga-organic-chia-seeds-3lb.jfif', altText: 'Mayorga Organics Chia Seeds', isPrimary: true }],
    inStock: true,
    stockQuantity: 60,
    ratingAverage: 4.8,
    reviewCount: 88,
    specifications: [{ label: 'Weight', value: '3 lbs (1.36 kg)' }],
    updatedAt: new Date().toISOString(),
  },

  // --- HEALTH & SUPPLEMENTS ---
  {
    id: 'prod-006',
    slug: 'nature-made-vitamin-d3-2000-iu',
    gtin: '031604026548',
    name: 'Nature Made Vitamin D3 1000 IU (25 mcg)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'Pharmacist recommended USP verified softgels supporting bone, teeth, muscle, and immune health (300 Softgels).',
    price: 14.99,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-vitamin-d3-2000-iu.avif', altText: 'Nature Made Vitamin D3 Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 100,
    ratingAverage: 4.9,
    reviewCount: 420,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    slug: 'youtheory-verisol-collagen-345-tablets',
    gtin: '085324400330',
    name: 'Youtheory VERISOL Collagen Advanced Formula',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'collagen',
    description: 'Concentrated effect formula with Biotin & Antioxidants to minimize wrinkles and improve skin elasticity (345 Tablets).',
    price: 21.99,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-verisol-collagen-345-tablets.avif', altText: 'Youtheory VERISOL Collagen', isPrimary: true }],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 175,
    specifications: [{ label: 'Count', value: '345 Tablets' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    slug: 'youtheory-ashwagandha-1000mg-180-capsules',
    gtin: '085324400385',
    name: 'Youtheory Ashwagandha 1000 mg',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'herbal',
    description: 'Daily adaptogen formula supporting a healthy stress response (180 Vegetarian Capsules).',
    price: 19.49,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-ashwagandha-1000mg-180-capsules.avif', altText: 'Youtheory Ashwagandha Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.8,
    reviewCount: 92,
    specifications: [{ label: 'Count', value: '180 Vegetarian Capsules' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    slug: 'nature-made-fish-oil-2400mg-300-softgels',
    gtin: '031604015283',
    name: 'Nature Made Fish Oil 2400 mg (720 mg Omega-3)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'omega-3',
    description: 'Purified to remove mercury. Supports a healthy heart (300 Softgels / 150 Doses).',
    price: 22.99,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-fish-oil-2400mg-300-softgels.avif', altText: 'Nature Made Fish Oil Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 70,
    ratingAverage: 4.9,
    reviewCount: 280,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },

  // --- PERSONAL CARE & HYGIENE ---
  {
    id: 'prod-010',
    slug: 'dove-original-beauty-bar-16-pack',
    gtin: '011111613769',
    name: 'Dove Original Beauty Bar Soap (16 Pack)',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'bar-soap',
    description: 'Classic moisturizing bar cleanser formulated with 1/4 moisturizing cream to leave skin soft, smooth, and nourished.',
    price: 18.99,
    currency: 'BIRR',
    images: [
      {
        url: '/products/dove-16-bars.avif',
        altText: 'Dove Original Beauty Bar Soap 16 Pack Box',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.9,
    reviewCount: 530,
    specifications: [
      { label: 'Count', value: '16 Bars' },
      { label: 'Net Weight', value: '60 oz Total (16 x 3.75 oz / 106g)' },
      { label: 'Formula', value: '1/4 Moisturizing Cream, Sulfate-Free' },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    slug: 'cetaphil-moisturizing-lotion-2pack',
    gtin: '302993910202',
    name: 'Cetaphil Moisturizing Lotion (2 Pack)',
    brand: 'Cetaphil',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: 'Lightweight lotion with Glycerin, Vitamins B3 & B5 for normal to dry skin hydration (Two 20 fl oz bottles).',
    price: 18.99,
    currency: 'BIRR',
    images: [{ url: '/products/cetaphil-moisturizing-lotion-2pack.avif', altText: 'Cetaphil Moisturizing Lotion 2-Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 410,
    specifications: [{ label: 'Volume', value: '40 fl oz Total (2 x 20 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    slug: 'cerave-facial-moisturizing-lotion-3pack',
    gtin: '360600053738',
    name: 'CeraVe AM/PM Facial Moisturizing Bundle (3 Pack)',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: '3 essential ceramides formula including AM Broad Spectrum SPF 30 lotion (3 Pack bundle).',
    price: 24.99,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-facial-moisturizing-lotion-3pack.avif', altText: 'CeraVe Facial Moisturizing Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.8,
    reviewCount: 320,
    specifications: [{ label: 'Set Includes', value: 'Facial Lotion AM SPF 30 & PM Lotions' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    slug: 'old-spice-swagger-deodorant-4pack',
    gtin: '037000976521',
    name: 'Old Spice Swagger Aluminum-Free Deodorant (4 Pack)',
    brand: 'Old Spice',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorant',
    description: 'Long-lasting 24/7 freshness with Cedarwood scent (Four 3.0 oz deodorant sticks).',
    price: 14.99,
    currency: 'BIRR',
    images: [{ url: '/products/old-spice-4pack.avif', 
               altText: 'Old Spice Swagger Deodorant 4-Pack', 
               isPrimary: true }
            ],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 195,
    specifications: [{ label: 'Weight', value: '12 oz Total (4 x 3.0 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    slug: 'olay-essential-botanicals-body-wash-3pack',
    gtin: '037000847164',
    name: 'Olay Essential Botanicals Body Wash (3 Pack)',
    brand: 'Olay',
    categorySlug: 'personal-care',
    subCategorySlug: 'body-wash',
    description: 'Nourishing body wash trio infused with essential botanicals and Vitamin B3 complex. Includes Lavender Milk & Sandalwood, Spiced Chai & Pear, and White Tea & Cucumber.',
    price: 18.49,
    currency: 'BIRR',
    images: [
      {
        url: '/products/olay-3-body- washes.jpg',
        altText: 'Olay Essential Botanicals Body Wash 3-Pack',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.9,
    reviewCount: 168,
    specifications: [
      { label: 'Volume', value: '70.8 fl oz Total (3 x 23.6 fl oz / 700 mL)' },
      {
        label: 'Scents Included',
        value: 'Lavender Milk & Sandalwood, Spiced Chai & Pear, White Tea & Cucumber',
      },
      { label: 'Key Ingredient', value: 'Vitamin B3 Complex' },
    ],
    updatedAt: new Date().toISOString(),
  },
];

export async function getProductBySlug(slug: string): Promise<Product | null> {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) || null;
}