import { Product } from '@/types/ecommerce';

export const MOCK_PRODUCTS: Product[] = [
  // --- PANTRY & CONFECTIONERY ---
  {
    id: 'prod-001',
    slug: 'kirkland-unsalted-mixed-nuts-2-5lb',
    gtin: '096619284218',
    name: 'Kirkland Extra Fancy Unsalted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Premium mix of cashews, almonds, pistachios, and macadamia nuts roasted without salt (2.5 lb / 1.13 kg).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-unsalted-mixed-nuts-2-5lb.avif', altText: 'Kirkland Unsalted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 140,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    slug: 'kirkland-salted-mixed-nuts-2-5lb',
    gtin: '096619164557',
    name: 'Kirkland Extra Fancy Salted Mixed Nuts',
    brand: 'Kirkland Signature',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Roasted mixed nuts with cashews, almonds, pecans, Brazil nuts, and macadamias lightly salted (2.5 lb / 1.13 kg).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/kirkland-salted-mixed-nuts-2-5lb-blue.jfif', altText: 'Kirkland Salted Mixed Nuts', isPrimary: true }],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.8,
    reviewCount: 95,
    specifications: [{ label: 'Weight', value: '2.5 lbs (1.13 kg)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    slug: 'lindt-lindor-assorted-truffles-21-2oz',
    gtin: '003746601633',
    name: 'Lindt LINDOR Assorted Chocolate Truffles',
    brand: 'Lindt',
    categorySlug: 'pantry',
    subCategorySlug: 'confectionery',
    description: 'Irresistibly smooth assorted chocolate truffles including milk, dark, white, and extra dark (21.2 oz / 600g).',
    price: 3500,
    currency: 'BIRR',
    images: [{ url: '/products/lindt-lindor-assorted-truffles-21-2oz.avif', altText: 'Lindt Lindor Assorted Truffles', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.9,
    reviewCount: 210,
    specifications: [{ label: 'Weight', value: '21.2 oz (600 g)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    slug: 'nutella-hazelnut-spread-2-pack',
    gtin: '009800895200',
    name: 'Nutella Hazelnut Spread with Cocoa (2 Pack)',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'spreads',
    description: 'Original rich hazelnut and cocoa spread bundle (Two 33.5 oz / 950g jars).',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/nutella-hazelnut-spread-2-pack.avif', altText: 'Nutella Hazelnut Spread Twin Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 25,
    ratingAverage: 5.0,
    reviewCount: 310,
    specifications: [{ label: 'Net Weight', value: '67 oz Total (2 x 33.5 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    slug: 'mayorga-organic-chia-seeds-3lb',
    gtin: '089708000215',
    name: 'Mayorga Organics BIRRA Chia Seeds',
    brand: 'Mayorga Organics',
    categorySlug: 'pantry',
    subCategorySlug: 'nuts-seeds',
    description: 'Small farmer direct organic non-GMO gluten-free chia seeds (3 lb / 1.36 kg).',
    price: 5790,
    currency: 'BIRR',
    images: [{ url: '/products/mayorga-organic-chia-seeds-3lb.jfif', altText: 'Mayorga Organics Chia Seeds', isPrimary: true }],
    inStock: true,
    stockQuantity: 60,
    ratingAverage: 4.8,
    reviewCount: 88,
    specifications: [{ label: 'Weight', value: '3 lbs (1.36 kg)' }],
    updatedAt: new Date().toISOString(),
  },

  // --- HEALTH & SUPPLEMENTS ---
  {
    id: 'prod-006',
    slug: 'nature-made-vitamin-d3-2000-iu',
    gtin: '031604026548',
    name: 'Nature Made Vitamin D3 1000 IU (25 mcg)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'Pharmacist recommended USP verified softgels supporting bone, teeth, muscle, and immune health (300 Softgels).',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-vitamin-d3-2000-iu.avif', altText: 'Nature Made Vitamin D3 Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 100,
    ratingAverage: 4.9,
    reviewCount: 420,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    slug: 'youtheory-verisol-collagen-345-tablets',
    gtin: '085324400330',
    name: 'Youtheory VERISOL Collagen Advanced Formula',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'collagen',
    description: 'Concentrated effect formula with Biotin & Antioxidants to minimize wrinkles and improve skin elasticity (345 Tablets).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-verisol-collagen-345-tablets.avif', altText: 'Youtheory VERISOL Collagen', isPrimary: true }],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 175,
    specifications: [{ label: 'Count', value: '345 Tablets' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    slug: 'youtheory-ashwagandha-1000mg-180-capsules',
    gtin: '085324400385',
    name: 'Youtheory Ashwagandha 1000 mg',
    brand: 'Youtheory',
    categorySlug: 'supplements',
    subCategorySlug: 'herbal',
    description: 'Daily adaptogen formula supporting a healthy stress response (180 Vegetarian Capsules).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/youtheory-ashwagandha-1000mg-180-capsules.avif', altText: 'Youtheory Ashwagandha Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.8,
    reviewCount: 92,
    specifications: [{ label: 'Count', value: '180 Vegetarian Capsules' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    slug: 'nature-made-fish-oil-2400mg-300-softgels',
    gtin: '031604015283',
    name: 'Nature Made Fish Oil 2400 mg (720 mg Omega-3)',
    brand: 'Nature Made',
    categorySlug: 'supplements',
    subCategorySlug: 'omega-3',
    description: 'Purified to remove mercury. Supports a healthy heart (300 Softgels / 150 Doses).',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/nature-made-fish-oil-2400mg-300-softgels.avif', altText: 'Nature Made Fish Oil Bottle', isPrimary: true }],
    inStock: true,
    stockQuantity: 70,
    ratingAverage: 4.9,
    reviewCount: 280,
    specifications: [{ label: 'Count', value: '300 Softgels' }],
    updatedAt: new Date().toISOString(),
  },

  // --- PERSONAL CARE & HYGIENE ---
  {
    id: 'prod-010',
    slug: 'dove-original-beauty-bar-16-pack',
    gtin: '011111613769',
    name: 'Dove Original Beauty Bar Soap (1 piece)',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'bar-soap',
    description: 'Classic moisturizing bar cleanser formulated with 1/4 moisturizing cream to leave skin soft, smooth, and nourished.',
    price: 350,
    currency: 'BIRR',
    images: [
      {
        url: '/products/dove-16-bars.avif',
        altText: 'Dove Original Beauty Bar Soap 16 Pack Box',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 40,
    ratingAverage: 4.9,
    reviewCount: 530,
    specifications: [
      { label: 'Count', value: '16 Bars' },
      { label: 'Net Weight', value: '60 oz Total (16 x 3.75 oz / 106g)' },
      { label: 'Formula', value: '1/4 Moisturizing Cream, Sulfate-Free' },
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    slug: 'cetaphil-moisturizing-lotion-2pack',
    gtin: '302993910202',
    name: 'Cetaphil Moisturizing Lotion',
    brand: 'Cetaphil',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: 'Lightweight lotion with Glycerin, Vitamins B3 & B5 for normal to dry skin hydration (Two 20 fl oz bottles).',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/cetaphil-moisturizing-lotion-2pack.avif', altText: 'Cetaphil Moisturizing Lotion 2-Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 50,
    ratingAverage: 4.9,
    reviewCount: 410,
    specifications: [{ label: 'Volume', value: '40 fl oz Total (2 x 20 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    slug: 'cerave-facial-moisturizing-lotion-3pack',
    gtin: '360600053738',
    name: 'CeraVe AM/PM Facial Moisturizing',
    brand: 'CeraVe',
    categorySlug: 'personal-care',
    subCategorySlug: 'lotions',
    description: '3 essential ceramides formula including AM Broad Spectrum SPF 30 lotion (3 Pack bundle).',
    price: 3800,
    currency: 'BIRR',
    images: [{ url: '/products/cerave-facial-moisturizing-lotion-3pack.avif', altText: 'CeraVe Facial Moisturizing Pack', isPrimary: true }],
    inStock: true,
    stockQuantity: 30,
    ratingAverage: 4.8,
    reviewCount: 320,
    specifications: [{ label: 'Set Includes', value: 'Facial Lotion AM SPF 30 & PM Lotions' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    slug: 'old-spice-swagger-deodorant-4pack',
    gtin: '037000976521',
    name: 'Old Spice Swagger Aluminum-Free Deodorant',
    brand: 'Old Spice',
    categorySlug: 'personal-care',
    subCategorySlug: 'deodorant',
    description: 'Long-lasting 24/7 freshness with Cedarwood scent (Four 3.0 oz deodorant sticks).',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/old-spice-4pack.avif', 
               altText: 'Old Spice Swagger Deodorant 4-Pack', 
               isPrimary: true }
            ],
    inStock: true,
    stockQuantity: 45,
    ratingAverage: 4.7,
    reviewCount: 195,
    specifications: [{ label: 'Weight', value: '12 oz Total (4 x 3.0 oz)' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    slug: 'olay-essential-botanicals-body-wash-3pack',
    gtin: '037000847164',
    name: 'Olay Essential Botanicals Body Wash',
    brand: 'Olay',
    categorySlug: 'personal-care',
    subCategorySlug: 'body-wash',
    description: 'Nourishing body wash trio infused with essential botanicals and Vitamin B3 complex. Includes Lavender Milk & Sandalwood, Spiced Chai & Pear, and White Tea & Cucumber.',
    price: 5000,
    currency: 'BIRR',
    images: [
      {
        url: '/products/olay-3-body-washes.jpg',
        altText: 'Olay Essential Botanicals Body Wash 3-Pack',
        isPrimary: true,
      },
    ],
    inStock: true,
    stockQuantity: 35,
    ratingAverage: 4.9,
    reviewCount: 168,
    specifications: [
      { label: 'Volume', value: '70.8 fl oz Total (3 x 23.6 fl oz / 700 mL)' },
      {
        label: 'Scents Included',
        value: 'Lavender Milk & Sandalwood, Spiced Chai & Pear, White Tea & Cucumber',
      },
      { label: 'Key Ingredient', value: 'Vitamin B3 Complex' },
    ],
    updatedAt: new Date().toISOString(),
  },

  // --- MATERIALS FROM THE STORE MATERIALS EXCEL SHEET (NON-DUPLICATE ITEMS) ---
  {
    id: 'prod-015',
    slug: 'colgate-total',
    gtin: '',
    name: 'Colgate Total',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Colgate Total',
    price: 2300,
    currency: 'BIRR',
    images: [{ url: '/products/colgate-total.avif', altText: 'Colgate Total', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-016',
    slug: 'gillette-ultimate-protection',
    gtin: '',
    name: 'Gillette Ultimate Protection',
    brand: 'Gillette',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Gillette Ultimate Protection',
    price: 2900,
    currency: 'BIRR',
    images: [{ url: '/products/Gillette-Ultimate-Protection.jfif', altText: 'Gillette Ultimate Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-017',
    slug: 'cheerios',
    gtin: '',
    name: 'Cheerios',
    brand: 'Cheerios',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Cheerios',
    price: 2000,
    currency: 'BIRR',
    images: [{ url: '/products/Cheerios-Oats.jfif', altText: 'Cheerios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000 old price' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-018',
    slug: 'krkland-organic-maple-syrup',
    gtin: '',
    name: 'Krkland Organic Maple Syrup',
    brand: 'Krkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Krkland Organic Maple Syrup. Source price: . Price was not provided in the source sheet.',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Krkland-Organic-Maple-Syrup.jfif', altText: 'Krkland Organic Maple Syrup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-019',
    slug: 'kirkland-organic-honey',
    gtin: '',
    name: 'Kirkland Organic Honey',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Kirkland Organic Honey',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Organic-Honey.jpg', altText: 'Kirkland Organic Honey', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-020',
    slug: 'dove-advanced-care-invisible',
    gtin: '',
    name: 'Dove Advanced Care Invisible',
    brand: 'Dove',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Dove Advanced Care Invisible. Source price: 2400. For a price range, the maximum price was used.',
    price: 2400,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Advanced-Care-Invisible.avif', altText: 'Dove Advanced Care Invisible', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2400' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-021',
    slug: 'dove-intensive-repair',
    gtin: '',
    name: 'Dove Intensive Repair',
    brand: 'Dove',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Dove Intensive Repair',
    price: 5000,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Intensive-Repair.avif', altText: 'Dove Intensive Repair', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4500-5000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-022',
    slug: 'jif-creamy-peanut-butter',
    gtin: '',
    name: 'Jif Creamy Peanut Butter',
    brand: 'Jif',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Jif Creamy Peanut Butter',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/Jif-Creamy-Peanut-Butter.jfif', altText: 'Jif Creamy Peanut Butter', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-023',
    slug: 'cinnamon-toast-crunch',
    gtin: '',
    name: 'Cinnamon Toast Crunch',
    brand: 'Cinnamon',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Cinnamon Toast Crunch',
    price: 4900,
    currency: 'BIRR',
    images: [{ url: '/products/Cinnamon-Toast-Crunch.jfif', altText: 'Cinnamon Toast Crunch', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000-4900' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-024',
    slug: 'tresemme-hydration-smoothness-and-shine',
    gtin: '',
    name: 'Tresemme Hydration Smoothness and Shine',
    brand: 'Tresemme',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Tresemme Hydration Smoothness and Shine',
    price: 8000,
    currency: 'BIRR',
    images: [{ url: '/products/Tresemme-Hydration-Smoothness-and-Shine.jfif', altText: 'Tresemme Hydration Smoothness and Shine', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '8000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-025',
    slug: 'aveeno-daily-moisturizing-lotion',
    gtin: '',
    name: 'Aveeno Daily Moisturizing Lotion',
    brand: 'Aveeno',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Aveeno Daily Moisturizing Lotion',
    price: 5500,
    currency: 'BIRR',
    images: [{ url: '/products/Aveeno-Daily-Moisturizing-Lotion.jpg', altText: 'Aveeno Daily Moisturizing Lotion', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '5000-5500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-026',
    slug: 'sensodyne-sensitivity-protection',
    gtin: '',
    name: 'Sensodyne Sensitivity Protection',
    brand: 'Sensodyne',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Sensodyne Sensitivity Protection',
    price: 3300,
    currency: 'BIRR',
    images: [{ url: '/products/Sensodyne-Sensitivity-Protection.jpg', altText: 'Sensodyne Sensitivity Protection', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-3300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-027',
    slug: 'crest-pro-health-advanced',
    gtin: '',
    name: 'Crest Pro-Health Advanced',
    brand: 'Crest',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Crest Pro-Health Advanced',
    price: 2500,
    currency: 'BIRR',
    images: [{ url: '/products/Crest-Pro-Health-Advanced.avif', altText: 'Crest Pro-Health Advanced', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2000-2500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-028',
    slug: 'irish-spring',
    gtin: '',
    name: 'Irish Spring',
    brand: 'Irish',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Irish Spring',
    price: 700,
    currency: 'BIRR',
    images: [{ url: '/products/Irish-Spring.jfif', altText: 'Irish Spring', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500-700' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-029',
    slug: 'kirkland-pistachios',
    gtin: '',
    name: 'Kirkland Pistachios',
    brand: 'Kirkland',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Kirkland Pistachios',
    price: 6000,
    currency: 'BIRR',
    images: [{ url: '/products/Kirkland-Pistachios.jpg', altText: 'Kirkland Pistachios', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-030',
    slug: 'trident',
    gtin: '',
    name: 'Trident',
    brand: 'Trident',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Trident',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/Trident-gum.jpg', altText: 'Trident', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-031',
    slug: 'degree-ultra-clear',
    gtin: '',
    name: 'Degree Ultra Clear',
    brand: 'Degree',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Degree Ultra Clear',
    price: 2300,
    currency: 'BIRR',
    images: [{ url: '/products/Degree-Ultra-Clear.avif', altText: 'Degree Ultra Clear', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2300' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-032',
    slug: 'extra-long-lasting-flavor',
    gtin: '',
    name: 'Extra Long Lasting Flavor',
    brand: 'Extra',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Extra Long Lasting Flavor',
    price: 500,
    currency: 'BIRR',
    images: [{ url: '/products/Extra-Long-Lasting-Flavor.jpg', altText: 'Extra Long Lasting Flavor', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-033',
    slug: 'oreo',
    gtin: '',
    name: 'Oreo',
    brand: 'Oreo',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Oreo',
    price: 1000,
    currency: 'BIRR',
    images: [{ url: '/products/Oreo-biscuts.jpg', altText: 'Oreo', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '1000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-034',
    slug: 'dove-deep-moisture',
    gtin: '',
    name: 'Dove Deep Moisture',
    brand: 'Dove',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Dove Deep Moisture',
    price: 4000,
    currency: 'BIRR',
    images: [{ url: '/products/Dove-Deep-Moisture.avif', altText: 'Dove Deep Moisture', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '4000' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-038',
    slug: 'one-a-day-womans-complete-multi-vitamin',
    gtin: '',
    name: 'One A Day Womans Complete Multi-vitamin',
    brand: 'One',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'One A Day Womans Complete Multi-vitamin',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/One-A-Day-Womans-Complete-Multi-vitamin.avif', altText: 'One A Day Womans Complete Multi-vitamin', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '6500-7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-039',
    slug: 'nature-made-prenatal',
    gtin: '',
    name: 'Nature Made Prenatal',
    brand: 'Nature',
    categorySlug: 'supplements',
    subCategorySlug: 'vitamins',
    description: 'Nature Made Prenatal',
    price: 7500,
    currency: 'BIRR',
    images: [{ url: '/products/Nature-Made-Prenatal.avif', altText: 'Nature Made Prenatal', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '7500' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-040',
    slug: 'heinz-tomato-ketchup',
    gtin: '',
    name: 'Heinz Tomato Ketchup',
    brand: 'Heinz',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Heinz Tomato Ketchup',
    price: 2800,
    currency: 'BIRR',
    images: [{ url: '/products/Heinz-Tomato-Ketchup.jfif', altText: 'Heinz Tomato Ketchup', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '2500-2800' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-041',
    slug: 'sc-johnson-ziplock',
    gtin: '',
    name: 'Sc Johnson Ziplock',
    brand: 'Sc',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Sc Johnson Ziplock',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Sc-Johnson-Ziplock.jpg', altText: 'Sc Johnson Ziplock', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-042',
    slug: 'nutella-peanut',
    gtin: '',
    name: 'Nutella Peanut',
    brand: 'Nutella',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Nutella Peanut',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Nutella-Peanut.jfif', altText: 'Nutella Peanut', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-043',
    slug: 'shin-raymun',
    gtin: '',
    name: 'Shin Raymun',
    brand: 'Shin',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Shin Raymun',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Shin-Raymun.jfif', altText: 'Shin Raymun', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-044',
    slug: 'febreze-air-freshner',
    gtin: '',
    name: 'Febreze Air Freshner',
    brand: 'Febreze',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Febreze Air Freshner',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Febreze-Air-Freshner.jpg', altText: 'Febreze Air Freshner', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-045',
    slug: 'desitin-maximum-strength-paste',
    gtin: '',
    name: 'Desitin Maximum Strength Paste',
    brand: 'Desitin',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Desitin Maximum Strength Paste',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Desitin-Maximum-Strength-Paste.jpg', altText: 'Desitin Maximum Strength Paste', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-046',
    slug: 'colgate-individually-sealed-brushes',
    gtin: '',
    name: 'Colgate Individually Sealed Brushes',
    brand: 'Colgate',
    categorySlug: 'personal-care',
    subCategorySlug: 'personal-care',
    description: 'Colgate Individually Sealed Brushes',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Colgate-Individually-Sealed-Brushes.jpg', altText: 'Colgate Individually Sealed Brushes', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-047',
    slug: 'blush-cardigen-fine-fregrance-mist',
    gtin: '',
    name: 'Blush Cardigen Fine Fregrance Mist',
    brand: 'Blush',
    categorySlug: 'pantry',
    subCategorySlug: 'groceries',
    description: 'Blush Cardigen Fine Fregrance Mist',
    price: 0,
    currency: 'BIRR',
    images: [{ url: '/products/Blush-Cardigen-Fine-Fregrance Mist.webp', altText: 'Blush Cardigen Fine Fregrance Mist', isPrimary: true }],
    inStock: false,
    stockQuantity: 0,
    ratingAverage: 0,
    reviewCount: 0,
    specifications: [{ label: 'Source Price', value: '' }],
    updatedAt: new Date().toISOString(),
  },
];

export async function getProductBySlug(slug: string): Promise<Product | null> {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) || null;
}